// apps/web/questions/user-interface/accordion-ii/frameworks/react/solution/setup/Accordion.js
import { useId, useState } from 'react';

function getAccordionHeaderId(accordionId, value) {
  return accordionId + '-header-' + value;
}

function getAccordionPanelId(accordionId, value) {
  return accordionId + '-panel-' + value;
}

export default function Accordion({ sections }) {
  const accordionId = useId();
  const [openSections, setOpenSections] = useState(
    new Set(),
  );

  return (
    <div className="accordion">
      {sections.map(({ value, title, contents }) => {
        const isExpanded = openSections.has(value);
        const headerId = getAccordionHeaderId(
          accordionId,
          value,
        );
        const panelId = getAccordionPanelId(
          accordionId,
          value,
        );

        return (
          <div className="accordion-item" key={value}>
            <button
              aria-controls={panelId}
              aria-expanded={isExpanded}
              id={headerId}
              className="accordion-item-title"
              type="button"
              onClick={() => {
                const newOpenSections = new Set(
                  openSections,
                );
                newOpenSections.has(value)
                  ? newOpenSections.delete(value)
                  : newOpenSections.add(value);
                setOpenSections(newOpenSections);
              }}>
              {title}{' '}
              <span
                aria-hidden={true}
                className={[
                  'accordion-icon',
                  isExpanded && 'accordion-icon--rotated',
                ]
                  .filter(Boolean)
                  .join(' ')}
              />
            </button>
            <div
              aria-labelledby={headerId}
              role="region"
              className="accordion-item-contents"
              id={panelId}
              hidden={!isExpanded}>
              {contents}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// contents/questions/user-interface/accordion-ii/frameworks/angular/solution/setup/src/app/accordion/accordion.component.ts
import { Component, Input } from '@angular/core';
import { Section } from '../app.component';

export function generateId(): string {
  return Math.random().toString(36).substring(2);
}

@Component({
  selector: 'app-accordion',
  templateUrl: './accordion.component.html',
  styleUrls: ['./accordion.component.css'],
})
export class AccordionComponent {
  @Input()
  sections!: Section[];

  openSections = new Set<string>();

  getAccordionHeaderId(
    accordionId: string,
    value: string,
  ): string {
    return accordionId + '-header-' + value;
  }

  getAccordionPanelId(
    accordionId: string,
    value: string,
  ): string {
    return accordionId + '-panel-' + value;
  }

  accordionId = generateId();

  isOpen(value: string): boolean {
    return this.openSections.has(value);
  }

  toggleSection(value: string): void {
    if (this.openSections.has(value)) {
      this.openSections.delete(value);
    } else {
      this.openSections.add(value);
    }
  }
}

<div class="wrapper">
  <div class="accordion">
    <div
      *ngFor="let section of sections; let i = index"
      class="accordion-item">
      <button
        [attr.aria-controls]="
          getAccordionPanelId(accordionId, section.value)
        "
        [attr.aria-expanded]="
          openSections.has(section.value)
        "
        [id]="
          getAccordionHeaderId(accordionId, section.value)
        "
        class="accordion-item-title"
        type="button"
        (click)="toggleSection(section.value)">
        {{ section.title }}
        <span
          [attr.aria-hidden]="true"
          [ngClass]="{
            'accordion-icon': true,
            'accordion-icon--rotated': isOpen(section.value)
          }">
        </span>
      </button>
      <div
        [attr.aria-labelledby]="
          getAccordionHeaderId(accordionId, section.value)
        "
        [id]="
          getAccordionPanelId(accordionId, section.value)
        "
        role="region"
        class="accordion-item-contents"
        [hidden]="!isOpen(section.value)">
        {{ section.contents }}
      </div>
    </div>
  </div>
</div>
