// contents/questions/user-interface/mortgage-calculator/setup/svelte/solution/src/App.svelte
<script>
  import './styles.css';

  let monthlyPayment = '';
  let totalPayment = '';
  let totalInterest = '';

  function onSubmit(event) {
    event.preventDefault(); // Prevent page reload on form submission.

    const data = new FormData(event.target);

    // Get and convert input values.
    const loanAmount = parseFloat(data.get('loan-amount'));
    const monthlyInterestRate =
      parseFloat(data.get('interest-rate')) / 100 / 12;
    const loanTermInMonths =
      parseFloat(data.get('loan-term')) * 12;

    // Calculate monthly mortgage payment.
    const monthlyPaymentAmount =
      (loanAmount * monthlyInterestRate) /
      (1 -
        1 /
          Math.pow(
            1 + monthlyInterestRate,
            loanTermInMonths,
          ));
    const totalPaymentAmount =
      monthlyPaymentAmount * loanTermInMonths;

    const currencyFormatter = new Intl.NumberFormat(
      'en-US',
      {
        style: 'currency',
        currency: 'USD',
      },
    );

    // Display monthly payment amount.
    monthlyPayment = currencyFormatter.format(
      monthlyPaymentAmount,
    );
    // Display total payment amount.
    totalPayment = currencyFormatter.format(
      totalPaymentAmount,
    );
    // Display total interest amount.
    totalInterest = currencyFormatter.format(
      totalPaymentAmount - loanAmount,
    );
  }
</script>

<div class="mortgage-calculator">
  <form
    class="mortgage-calculator-form"
    on:submit={onSubmit}>
    <div>
      <label>
        {'Loan Amount: '}
        <input
          type="number"
          name="loan-amount"
          defaultValue="100000"
          min="1"
          required />
      </label>
    </div>
    <div>
      <label>
        {'Loan Term (years): '}
        <input
          type="number"
          name="loan-term"
          defaultValue="30"
          min="1"
          required />
      </label>
    </div>
    <div>
      <label>
        {'Interest Rate (%): '}
        <input
          type="number"
          name="interest-rate"
          defaultValue="3"
          step="0.01"
          min="0.01"
          required />
      </label>
    </div>
    <div>
      <button type="submit">Calculate</button>
    </div>
  </form>
  <hr />
  <div
    aria-live="polite"
    class="mortgage-calculator-results">
    <div>
      {'Monthly Payment Amount: '}
      <strong>{monthlyPayment}</strong>
    </div>
    <div>
      {'Total Payment Amount: '}
      <strong>{totalPayment}</strong>
    </div>
    <div>
      {'Total Interest Paid: '}
      <strong>{totalInterest}</strong>
    </div>
  </div>
</div>

<style>
  .mortgage-calculator {
    display: flex;
    flex-direction: column;
    font-size: 14px;
    gap: 12px;
  }

  .mortgage-calculator-form {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .mortgage-calculator-results {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
</style>

// contents/questions/user-interface/generate-table/frameworks/vue/solution/setup/src/App.vue
<script setup>
import { ref } from 'vue';
import Table from './Table.vue';

const rows = ref();
const columns = ref();

function submitForm(event) {
  // Obtain data from the form.
  const data = new FormData(event.target);
  const rowsValue = data.get('rows');
  rows.value = Number(rowsValue);
  const columnsValue = data.get('columns');
  columns.value = Number(columnsValue);
}
</script>

<template>
  <div class="app">
    <!-- To prevent a page reload. -->
    <form @submit.prevent="submitForm">
      <div>
        <label for="rows">Rows</label>
        <input
          id="rows"
          name="rows"
          type="number"
          min="1"
          :defaultValue="rows" />
      </div>
      <div>
        <label for="columns">Columns</label>
        <input
          id="columns"
          name="columns"
          type="number"
          min="1"
          :defaultValue="columns" />
      </div>
      <button type="submit">Submit</button>
    </form>

    <Table
      v-if="rows && columns"
      :rows="rows"
      :columns="columns" />
  </div>
</template>

<style>
.app {
  align-items: center;
  display: flex;
  font-size: 12px;
  flex-direction: column;
  gap: 16px;
  justify-content: center;
}

form {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

label + input {
  margin-left: 8px;
}
</style>
