// packages/questions/user-interface/accordion-ii/frameworks/vue/skeleton/setup/src/Accordion.vue
<script setup>
import { ref } from 'vue';

const props = defineProps({
  sections: Array,
});

const openSections = ref(new Set());
</script>

<template>
  <div class="accordion">
    <div
      class="accordion-item"
      v-for="{ value, title, contents } in sections"
      :key="value">
      <button
        class="accordion-item-title"
        @click="
          () => {
            if (openSections.has(value)) {
              openSections.delete(value);
            } else {
              openSections.add(value);
            }
          }
        ">
        {{ title }}
        <span
          aria-hidden
          :class="[
            'accordion-icon',
            openSections.has(value) &&
              'accordion-icon--rotated',
          ]" />
      </button>
      <div
        class="accordion-item-contents"
        :hidden="!openSections.has(value)">
        {{ contents }}
      </div>
    </div>
  </div>
</template>

<style>
.accordion {
  display: flex;
  flex-direction: column;
  width: 100%;
}

.accordion-item {
  display: flex;
  flex-direction: column;
  row-gap: 4px;
  padding: 4px 0;
}

.accordion-item:not(:first-child) {
  border-top: 1px solid #eee;
}

.accordion-item-title {
  align-items: center;
  border: none;
  background: none;
  cursor: pointer;
  font-weight: 500;
  padding: 4px;
  justify-content: space-between;
  text-align: start;
  display: flex;
}

.accordion-item-title:hover {
  background-color: #eee;
}

.accordion-icon {
  border: solid currentcolor;
  border-width: 0 2px 2px 0;
  display: inline-block;
  height: 8px;
  pointer-events: none;
  transform: translateY(-2px) rotate(45deg);
  width: 8px;
}

.accordion-icon--rotated {
  transform: translateY(2px) rotate(-135deg);
}

.accordion-item-contents {
  font-size: 14px;
  line-height: 1.2em;
  padding: 4px;
}
</style>

// contents/questions/user-interface/accordion-ii/frameworks/svelte/skeleton/setup/src/Accordion.svelte
<script>
  export let sections;
  let openSections = new Set();
</script>

<div class="accordion">
  {#each sections as { value, title, contents }}
    {@const isExpanded = openSections.has(value)}

    <div class="accordion-item">
      <button
        class="accordion-item-title"
        on:click={() => {
          if (openSections.has(value)) {
            openSections.delete(value);
          } else {
            openSections.add(value);
          }
          openSections = openSections;
        }}>
        {title}
        <span
          aria-hidden={true}
          class="accordion-icon"
          class:accordion-icon--rotated={isExpanded} />
      </button>
      <div
        class="accordion-item-contents"
        hidden={!isExpanded}>
        {contents}
      </div>
    </div>
  {/each}
</div>

<style>
  .accordion {
    display: flex;
    flex-direction: column;
    width: 100%;
  }

  .accordion-item {
    display: flex;
    flex-direction: column;
    row-gap: 4px;
    padding: 4px 0;
  }

  .accordion-item:not(:first-child) {
    border-top: 1px solid #eee;
  }

  .accordion-item-title {
    align-items: center;
    border: none;
    background: none;
    cursor: pointer;
    font-weight: 500;
    padding: 4px;
    justify-content: space-between;
    text-align: start;
    display: flex;
  }

  .accordion-item-title:hover {
    background-color: #eee;
  }

  .accordion-icon {
    border: solid currentcolor;
    border-width: 0 2px 2px 0;
    display: inline-block;
    height: 8px;
    pointer-events: none;
    transform: translateY(-2px) rotate(45deg);
    width: 8px;
  }

  .accordion-icon--rotated {
    transform: translateY(2px) rotate(-135deg);
  }

  .accordion-item-contents {
    font-size: 14px;
    line-height: 1.2em;
    padding: 4px;
  }
</style>
