// packages/questions/user-interface/connect-four/frameworks/vue/solution/setup/src/PlayerMoveSection.vue
<script setup>
import { COLS, PLAYER_TOKENS } from './const';

defineProps({
  availableColumns: Set,
  currentColumn: Number,
  currentPlayer: Number,
  gameHasEnded: Boolean,
});
</script>

<template>
  <div class="player-move-section">
    <button
      v-for="(_, index) in COLS"
      :key="index"
      :aria-label="`Column ${index + 1}`"
      :disabled="
        !availableColumns.has(index) || gameHasEnded
      "
      :style="{
        'background-color':
          currentColumn === index && !gameHasEnded
            ? PLAYER_TOKENS[currentPlayer]
            : undefined,
      }"
      class="player-move-column"
      @mouseenter="$emit('column-hover', index)"
      @click="$emit('player-move', index)" />
  </div>
</template>

<style>
.player-move-section {
  display: flex;
  align-items: center;
  padding: var(--grid-item-gap);
  gap: var(--grid-item-gap);
}

.player-move-column {
  background-color: transparent;
  height: var(--grid-item-size);
  width: var(--grid-item-size);
  border-radius: 100%;
  transition: background-color 0.1s linear;
  outline: none;
  border: none;
  cursor: pointer;
}
</style>

// contents/questions/user-interface/connect-four/frameworks/svelte/solution/setup/src/PlayerMoveSection.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { COLS, PLAYER_TOKENS } from './const';
  export let availableColumns;
  export let currentColumn;
  export let currentPlayer;
  export let gameHasEnded;

  const dispatch = createEventDispatcher();
</script>

<div class="player-move-section">
  {#each { length: COLS } as _, index (index)}
    <button
      aria-label={`Column ${index + 1}`}
      disabled={!availableColumns.has(index) ||
        gameHasEnded}
      style:background-color={currentColumn === index &&
      !gameHasEnded
        ? PLAYER_TOKENS[currentPlayer]
        : undefined}
      class="player-move-column"
      on:mouseenter={() =>
        dispatch('column-hover', { index })}
      on:click={() => dispatch('player-move', { index })} />
  {/each}
</div>

<style>
  .player-move-section {
    display: flex;
    align-items: center;
    padding: var(--grid-item-gap);
    gap: var(--grid-item-gap);
  }

  .player-move-column {
    background-color: transparent;
    height: var(--grid-item-size);
    width: var(--grid-item-size);
    border-radius: 100%;
    transition: background-color 0.1s linear;
    outline: none;
    border: none;
    cursor: pointer;
  }
</style>
