// packages/questions/user-interface/transfer-list/frameworks/svelte/solution/setup/src/ItemList.svelte
<script>
  export let items;
</script>

<div class="transfer-list__section">
  <ul class="transfer-list__section__items">
    {#each Array.from(items.entries()) as [label, checked]}
      <li>
        <div class="transfer-list__section__items__item">
          <label>
            <input
              type="checkbox"
              {checked}
              on:change={() => {
                const newItems = new Map(items);
                newItems.set(label, !items.get(label));
                items = newItems;
              }} />
            {label}</label>
        </div>
      </li>
    {/each}
  </ul>
</div>

<style>
  ul {
    list-style-type: none;
    padding-left: 0;
  }

  .transfer-list__section {
    padding: 20px;
    flex-grow: 1;
  }

  .transfer-list__section__items {
    display: flex;
    flex-direction: column;
    row-gap: 12px;
  }

  .transfer-list__section__items__item {
    display: flex;
    gap: 8px;
  }
</style>

// contents/questions/user-interface/transfer-list/frameworks/angular/solution/setup/src/app/item-list.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
} from '@angular/core';

@Component({
  selector: 'app-item-list',
  templateUrl: './item-list.component.html',
  styles: [
    `
      :host {
        width: 100%;
      }
    `,
  ],
})
export class ItemListComponent {
  @Input()
  items!: Map<string, boolean>;

  @Output()
  updateItems = new EventEmitter<Map<string, boolean>>();

  get itemsArray() {
    return Array.from(this.items.entries());
  }

  toggleItem(label: string) {
    const newItems = new Map(this.items);
    newItems.set(label, !this.items.get(label));
    this.updateItems.emit(newItems);
  }
}

<div class="transfer-list__section">
  <ul class="transfer-list__section__items">
    <li *ngFor="let item of itemsArray">
      <div class="transfer-list__section__items__item">
        <input
          type="checkbox"
          [id]="item[0]"
          [checked]="item[1]"
          (change)="toggleItem(item[0])" />
        <label [for]="item[0]">{{ item[0] }}</label>
      </div>
    </li>
  </ul>
</div>
