// packages/questions/user-interface/traffic-light/frameworks/angular/solution/setup/src/app/traffic-light.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  Input,
} from '@angular/core';

type DefaultColors = 'green' | 'yellow' | 'red';

type ColorConfig<Colors> = {
  backgroundColor: string;
  duration: number;
  order: number;
  next: Colors;
};
export type TrafficLightConfig<
  Colors extends DefaultColors,
> = Record<Colors, ColorConfig<Colors>>;

@Component({
  selector: 'app-traffic-light',
  templateUrl: './traffic-light.component.html',
  styleUrls: ['./traffic-light.component.css'],
})
export class TrafficLightComponent<
  Colors extends DefaultColors,
> implements OnInit, OnDestroy
{
  @Input({ required: true }) initialColor!: Colors;
  @Input({ required: true })
  config!: TrafficLightConfig<Colors>;
  @Input() layout = 'vertical';

  currentColor!: Colors;
  timerId: ReturnType<typeof setInterval> | null = null;
  trafficLightOrder = (
    a: ColorConfig<Colors>,
    b: ColorConfig<Colors>,
  ) => (a.order > b.order ? -1 : 1);

  ngOnInit() {
    this.currentColor = this.initialColor;
    this.updateLight();
  }

  ngOnDestroy() {
    if (this.timerId) {
      clearTimeout(this.timerId);
    }
  }

  updateLight() {
    const { duration, next } =
      this.config[this.currentColor];

    this.timerId = setTimeout(() => {
      this.currentColor = next;
      this.updateLight();
    }, duration);
  }
}

<div
  aria-live="polite"
  [attr.aria-label]="'Current light: ' + currentColor"
  [ngClass]="{
    'traffic-light-container': true,
    'traffic-light-container--vertical':
      layout === 'vertical'
  }">
  <div
    *ngFor="
      let color of config | keyvalue: trafficLightOrder
    "
    [attr.aria-hidden]="true"
    class="traffic-light"
    [style.background-color]="
      color.key === currentColor
        ? config[color.key].backgroundColor
        : undefined
    "></div>
</div>

// contents/questions/user-interface/traffic-light/setup/react/solution/src/TrafficLight.js
import { useEffect, useState } from 'react';

function Light({ backgroundColor }) {
  return (
    <div
      aria-hidden={true}
      className="traffic-light"
      style={{ backgroundColor }}
    />
  );
}

export default function TrafficLight({
  initialColor = 'green',
  config,
  layout = 'vertical',
}) {
  const [currentColor, setCurrentColor] =
    useState(initialColor);

  useEffect(() => {
    const { duration, next } = config[currentColor];

    const timerId = setTimeout(() => {
      setCurrentColor(next);
    }, duration);

    return () => {
      clearTimeout(timerId);
    };
  }, [currentColor]);

  return (
    <div
      aria-live="polite"
      aria-label={`Current light: ${currentColor}`}
      className={[
        'traffic-light-container',
        layout === 'vertical' &&
          'traffic-light-container--vertical',
      ]
        .filter((cls) => !!cls)
        .join(' ')}>
      {Object.keys(config).map((color) => (
        <Light
          key={color}
          backgroundColor={
            color === currentColor
              ? config[color].backgroundColor
              : undefined
          }
        />
      ))}
    </div>
  );
}
