// contents/questions/user-interface/generate-table/frameworks/vue/solution/setup/src/App.vue
<script setup>
import { ref } from 'vue';
import Table from './Table.vue';

const rows = ref();
const columns = ref();

function submitForm(event) {
  // Obtain data from the form.
  const data = new FormData(event.target);
  const rowsValue = data.get('rows');
  rows.value = Number(rowsValue);
  const columnsValue = data.get('columns');
  columns.value = Number(columnsValue);
}
</script>

<template>
  <div class="app">
    <!-- To prevent a page reload. -->
    <form @submit.prevent="submitForm">
      <div>
        <label for="rows">Rows</label>
        <input
          id="rows"
          name="rows"
          type="number"
          min="1"
          :defaultValue="rows" />
      </div>
      <div>
        <label for="columns">Columns</label>
        <input
          id="columns"
          name="columns"
          type="number"
          min="1"
          :defaultValue="columns" />
      </div>
      <button type="submit">Submit</button>
    </form>

    <Table
      v-if="rows && columns"
      :rows="rows"
      :columns="columns" />
  </div>
</template>

<style>
.app {
  align-items: center;
  display: flex;
  font-size: 12px;
  flex-direction: column;
  gap: 16px;
  justify-content: center;
}

form {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

label + input {
  margin-left: 8px;
}
</style>

// contents/questions/user-interface/temperature-converter/frameworks/svelte/solution/setup/src/App.svelte
<script>
  let celsius;
  let fahrenheit;

  function round(number) {
    return Number(number.toFixed(4));
  }
</script>

<div class="temperature-converter">
  <label>
    <input
      class="temperature-converter-column-top-row"
      type="number"
      value={celsius}
      on:input={(event) => {
        celsius = event.target.value;
        fahrenheit = round((celsius * 9) / 5 + 32);
      }} />
    <div class="temperature-converter-column-bottom-row">
      Celsius
    </div>
  </label>
  <div>
    <div class="temperature-converter-column-top-row">
      =
    </div>
  </div>
  <label>
    <input
      class="temperature-converter-column-top-row"
      type="number"
      value={fahrenheit}
      on:input={(event) => {
        fahrenheit = event.target.value;
        celsius = round(((fahrenheit - 32) * 5) / 9);
      }} />
    <div class="temperature-converter-column-bottom-row">
      Fahrenheit
    </div>
  </label>
</div>

<style>
  .temperature-converter {
    display: flex;
  }

  .temperature-converter-column-top-row {
    align-items: center;
    display: flex;
    font-size: 18px;
    height: 24px;
    padding: 4px;
    text-align: center;
  }

  .temperature-converter-column-bottom-row {
    padding: 4px;
    text-align: center;
  }
</style>
