// apps/web/questions/user-interface/accordion/frameworks/react/skeleton/setup/Accordion.js
export default function Accordion() {
  return (
    <div>
      <div>
        <div>
          HTML{' '}
          <span
            aria-hidden={true}
            className="accordion-icon"
          />
        </div>
        <div>
          The HyperText Markup Language or HTML is the
          standard markup language for documents designed to
          be displayed in a web browser.
        </div>
      </div>
      <div>
        <div>
          CSS{' '}
          <span
            aria-hidden={true}
            className="accordion-icon"
          />
        </div>
        <div>
          Cascading Style Sheets is a style sheet language
          used for describing the presentation of a document
          written in a markup language such as HTML or XML.
        </div>
      </div>
      <div>
        <div>
          JavaScript{' '}
          <span
            aria-hidden={true}
            className="accordion-icon"
          />
        </div>
        <div>
          JavaScript, often abbreviated as JS, is a
          programming language that is one of the core
          technologies of the World Wide Web, alongside HTML
          and CSS.
        </div>
      </div>
    </div>
  );
}

// contents/questions/user-interface/accordion/setup/svelte/skeleton/src/Accordion.svelte
<div>
  <div>
    <div>
      HTML
      <span aria-hidden={true} class="accordion-icon" />
    </div>
    <div>
      The HyperText Markup Language or HTML is the standard
      markup language for documents designed to be displayed
      in a web browser.
    </div>
  </div>
  <div>
    <div>
      CSS
      <span aria-hidden={true} class="accordion-icon" />
    </div>
    <div>
      Cascading Style Sheets is a style sheet language used
      for describing the presentation of a document written
      in a markup language such as HTML or XML.
    </div>
  </div>
  <div>
    <div>
      JavaScript
      <span aria-hidden={true} class="accordion-icon" />
    </div>
    <div>
      JavaScript, often abbreviated as JS, is a programming
      language that is one of the core technologies of the
      World Wide Web, alongside HTML and CSS.
    </div>
  </div>
</div>

<style>
  .accordion-icon {
    border: solid currentcolor;
    border-width: 0 2px 2px 0;
    display: inline-block;
    height: 8px;
    pointer-events: none;
    transform: translateY(-2px) rotate(45deg);
    width: 8px;
  }

  .accordion-icon--rotated {
    transform: translateY(2px) rotate(-135deg);
  }
</style>
