// contents/questions/user-interface/pixel-art/frameworks/react/solution/setup/src/Canvas.tsx
import { useState } from 'react';

import Cell from './Cell';
import { Color, Mode } from './colors';

type Props = Readonly<{
  selectedColor: Color;
  initialRows?: number;
  initialColumns?: number;
  mode: Mode;
}>;

export default function Canvas({
  selectedColor,
  mode,
  initialRows = 15,
  initialColumns = 15,
}: Props) {
  const [grid, setGrid] = useState<(Color | null)[][]>(
    Array.from({ length: initialRows }, () =>
      Array(initialColumns).fill(null),
    ),
  );
  const [isDragging, setIsDragging] = useState(false);

  return (
    <div
      className="grid"
      onMouseDown={() => setIsDragging(true)}
      onMouseUp={() => setIsDragging(false)}>
      {grid.map((row, rowIndex) => (
        <div
          className={[
            'grid__row',
            rowIndex % 2 === 0
              ? 'grid__row--even'
              : 'grid__row--odd',
          ].join(' ')}
          key={rowIndex}>
          {row.map((cellColor, cellIndex) => (
            <Cell
              key={cellIndex}
              color={cellColor}
              isDragging={isDragging}
              onMark={() => {
                const newGrid = grid.map((row) => [...row]);
                newGrid[rowIndex][cellIndex] =
                  mode === 'erase' ? null : selectedColor;
                setGrid(newGrid);
              }}
            />
          ))}
        </div>
      ))}
    </div>
  );
}

// contents/questions/user-interface/pixel-art/frameworks/angular/solution/setup/src/app/canvas.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Color, COLORS, Mode } from './colors';

interface Cell {
  color: Color | null;
}

@Component({
  selector: 'app-canvas',
  templateUrl: './canvas.component.html',
})
export class CanvasComponent implements OnInit {
  @Input()
  selectedColor!: Color;

  @Input()
  mode!: Mode;

  initialRows: number = 15;
  initialColumns: number = 15;
  grid: Cell[][] = [];
  isDragging = false;
  COLORS = COLORS;

  ngOnInit() {
    this.createGrid();
  }

  createGrid(): void {
    this.grid = Array.from(
      { length: this.initialRows },
      () =>
        Array.from({ length: this.initialColumns }, () => ({
          color: null,
        })),
    );
  }

  onMark(rowIndex: number, cellIndex: number): void {
    const newGrid = this.grid.map((row) => [...row]);
    newGrid[rowIndex][cellIndex].color =
      this.mode === 'erase' ? null : this.selectedColor;
    this.grid = newGrid;
  }

  trackByFn(index: number) {
    return index;
  }
}
