// packages/questions/user-interface/digital-clock/frameworks/svelte/solution/setup/src/Separator.svelte
<div class="separator">
  <div class="separator-dot" />
  <div class="separator-dot" />
</div>

<style>
  .separator {
    align-items: center;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
  }

  .separator-dot {
    background-color: var(--segment-color);
    border-radius: var(--segment-width);
    height: var(--segment-width);
    width: var(--segment-width);
  }
</style>

// contents/questions/user-interface/digital-clock/frameworks/vue/solution/setup/src/Separator.vue
<template>
  <div class="separator">
    <div class="separator-dot" />
    <div class="separator-dot" />
  </div>
</template>

<style>
.separator {
  align-items: center;
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
}

.separator-dot {
  background-color: var(--segment-color);
  border-radius: var(--segment-width);
  height: var(--segment-width);
  width: var(--segment-width);
}
</style>
