// contents/questions/user-interface/flight-booker/frameworks/svelte/solution/setup/src/App.svelte
<script>
  import './styles.css';

  const TODAY = formatDate(new Date());
  const DAY_IN_SECONDS = 24 * 60 * 60 * 1000;

  let flightOption = 'one-way';
  let departureDate = formatDate(
    new Date(Date.now() + DAY_IN_SECONDS),
  );
  let returnDate = departureDate;

  function formatDate(date) {
    const year = date.getFullYear();
    const month = (date.getMonth() + 1)
      .toString()
      .padStart(2, '0');
    const day = date.getDate().toString().padStart(2, '0');

    return [year, month, day].join('-');
  }
</script>

<div>
  <form
    on:submit={(event) => {
      event.preventDefault();
      if (flightOption === 'one-way') {
        alert(
          `You have booked a one-way flight on ${departureDate}`,
        );
        return;
      }

      alert(
        `You have booked a return flight, departing on ${departureDate} and returning on ${returnDate}`,
      );
    }}>
    <select bind:value={flightOption}>
      <option value="one-way">One-way flight</option>
      <option value="return">Return flight</option>
    </select>
    <input
      aria-label="Departure date"
      type="date"
      bind:value={departureDate}
      min={TODAY} />

    {#if flightOption === 'return'}
      <input
        aria-label="Return date"
        type="date"
        bind:value={returnDate}
        min={departureDate} />
    {/if}
    <button>Book</button>
  </form>
</div>

<style>
  form {
    display: flex;
    flex-direction: column;
    gap: 12px;
    margin: 0 auto;
    max-width: 320px;
  }
</style>

// packages/questions/user-interface/flight-booker/frameworks/angular/solution/setup/src/app/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
} from '@angular/core';

type FlightOption = 'one-way' | 'return';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly TODAY: string = this.formatDate(new Date());
  readonly DAY_IN_SECONDS = 24 * 60 * 60 * 1000;

  flightOption: FlightOption = 'one-way';
  departureDate: string = this.formatDate(
    new Date(Date.now() + this.DAY_IN_SECONDS),
  );
  returnDate: string = this.departureDate;

  onSubmit() {
    if (this.flightOption === 'one-way') {
      alert(
        `You have booked a one-way flight on ${this.departureDate}`,
      );
      return;
    }

    alert(
      `You have booked a return flight, departing on ${this.departureDate} and returning on ${this.returnDate}`,
    );
  }

  private formatDate(date: Date): string {
    const year = date.getFullYear();
    const month = (date.getMonth() + 1)
      .toString()
      .padStart(2, '0');
    const day = date.getDate().toString().padStart(2, '0');
    return [year, month, day].join('-');
  }
}

<div>
  <form
    class="flight-booker"
    (ngSubmit)="onSubmit()"
    ngNativeValidate>
    <select [(ngModel)]="flightOption" name="flightOption">
      <option value="one-way">One-way flight</option>
      <option value="return">Return flight</option>
    </select>
    <input
      aria-label="Departure date"
      type="date"
      [(ngModel)]="departureDate"
      name="departureDate"
      [min]="TODAY" />
    <input
      *ngIf="flightOption !== 'one-way'"
      aria-label="Return date"
      type="date"
      [(ngModel)]="returnDate"
      name="returnDate"
      [min]="departureDate" />
    <button type="submit">Book</button>
  </form>
</div>
