// contents/questions/user-interface/analog-clock/setup/svelte/solution/src/Clock.svelte
<script>
  import { onMount } from 'svelte';
  import ClockImpl from './ClockImpl.svelte';

  let date = new Date();

  // Kick off the timer.
  onMount(() => {
    const timer = window.setInterval(() => {
      date = new Date();
    }, 100);

    // Clear the timer upon unmount.
    return () => {
      window.clearInterval(timer);
    };
  });

  $: hours = date.getHours() % 12;
  $: minutes = date.getMinutes();
  $: seconds = date.getSeconds();
</script>

<ClockImpl {hours} {minutes} {seconds} size={300} />

// contents/questions/user-interface/analog-clock/frameworks/vue/solution/setup/src/Clock.vue
<script setup>
import { computed } from 'vue';
import ClockImpl from './ClockImpl.vue';
import { useCurrentDate } from './composables';

const currentDate = useCurrentDate();

const currentTime = computed(() => {
  const currentDateValue = currentDate.value;
  const hours = currentDateValue.getHours() % 12;
  const minutes = currentDateValue.getMinutes();
  const seconds = currentDateValue.getSeconds();
  return {
    hours,
    minutes,
    seconds,
  };
});
</script>

<template>
  <ClockImpl
    :hours="currentTime.hours"
    :minutes="currentTime.minutes"
    :seconds="currentTime.seconds"
    :size="300" />
</template>
