// packages/questions/user-interface/pixel-art/frameworks/angular/solution/setup/src/app/toolbar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  Pipe,
  PipeTransform,
} from '@angular/core';
import { COLORS, Color, Mode } from './colors';

@Component({
  selector: 'app-toolbar',
  templateUrl: './toolbar.component.html',
})
export class ToolbarComponent {
  @Input()
  selectedColor!: Color;

  @Input()
  mode!: Mode;

  @Output()
  colorChange = new EventEmitter<Color>();

  @Output()
  modeChange = new EventEmitter<Mode>();

  COLORS = COLORS;

  onColorClick(color: string): void {
    this.modeChange.emit('draw');
    this.colorChange.emit(color as Color);
  }
}

@Pipe({ name: 'borderColor' })
export class BorderColorPipe implements PipeTransform {
  transform(
    color: string,
    selectedColor: string,
  ): string | undefined {
    if (color !== selectedColor && color === 'white') {
      return '#ccc';
    }
    if (color === selectedColor && color === 'black') {
      return '#fff';
    }
    return undefined;
  }
}

<div class="toolbar">
  <div>
    <button
      (click)="modeChange.emit('draw')"
      [ngClass]="{
        toolbar__mode: true,
        'toolbar__mode--selected': mode === 'draw'
      }">
      Draw
    </button>
    <button
      (click)="modeChange.emit('erase')"
      [ngClass]="{
        toolbar__mode: true,
        'toolbar__mode--selected': mode === 'erase'
      }">
      Erase
    </button>
  </div>
  <div class="toolbar__color-picker">
    <ng-container *ngFor="let entry of COLORS | keyvalue">
      <button
        [attr.aria-label]="entry.key"
        [ngClass]="{
          toolbar__color: true,
          'toolbar__color--selected':
            entry.key === selectedColor
        }"
        [ngStyle]="{
          'border-color':
            entry.key | borderColor: selectedColor,
          'background-color': entry.value
        }"
        (click)="onColorClick(entry.key)"></button>
    </ng-container>
  </div>
</div>

// packages/questions/user-interface/pixel-art/frameworks/vue/solution/setup/src/Toolbar.vue
<script setup lang="ts">
import { COLORS, Color, Mode } from './colors';

const props = defineProps<{
  mode: Mode;
  selectedColor: Color;
}>();

const emit = defineEmits<{
  'update:mode': [value: Mode];
  'update:selectedColor': [value: Color];
}>();
</script>

<template>
  <div class="toolbar">
    <div>
      <button
        @click="() => $emit('update:mode', 'draw')"
        :class="[
          'toolbar__mode',
          mode === 'draw' && 'toolbar__mode--selected',
        ]">
        Draw
      </button>
      <button
        @click="() => $emit('update:mode', 'erase')"
        :class="[
          'toolbar__mode',
          mode === 'erase' && 'toolbar__mode--selected',
        ]">
        Erase
      </button>
    </div>
    <div class="toolbar__color-picker">
      <button
        v-for="[color, hex] in Object.entries(COLORS)"
        :key="color"
        :aria-label="color"
        :class="[
          'toolbar__color',
          color === selectedColor &&
            'toolbar__color--selected',
        ]"
        :style="{
          'border-color': (() => {
            if (
              color !== selectedColor &&
              color === 'white'
            ) {
              return '#ccc';
            }

            if (
              color === selectedColor &&
              color === 'black'
            ) {
              return '#fff';
            }
          })(),
          'background-color': hex,
        }"
        @click="
          () => {
            $emit('update:selectedColor', color);
            $emit('update:mode', 'draw');
          }
        " />
    </div>
  </div>
</template>

<style>
.toolbar {
  display: flex;
  gap: 20px;
}

.toolbar .toolbar__mode {
  height: 36px;
  background-color: transparent;
  border: 2px solid black;
  font-size: 14px;
}

.toolbar .toolbar__mode--selected {
  background-color: black;
  color: white;
}

.toolbar .toolbar__color-picker {
  display: flex;
}

.toolbar .toolbar__color {
  --size: 20px;

  width: var(--size);
  height: var(--size);
  border: 2px solid transparent;
}

.toolbar .toolbar__color--selected {
  border: 2px solid black;
}
</style>
