// contents/questions/user-interface/tic-tac-toe-ii/setup/vue/solution/src/Cell.vue
<script setup>
const props = defineProps({
  index: Number,
  mark: String,
  disabled: Boolean,
  turn: String,
});
</script>

<template>
  <button
    :aria-label="
      props.mark == null
        ? `Mark cell ${props.index} as ${props.turn}`
        : undefined
    "
    class="cell"
    :disabled="props.disabled"
    @click="$emit('on-click')">
    <span aria-hidden>{{ mark }}</span>
  </button>
</template>

<style>
.cell {
  background-color: #fff;
  border: 1px solid #ccc;
  color: #000;
  font-size: min(48px, 10vw);
  font-weight: bold;
  vertical-align: middle;
  aspect-ratio: 1 / 1;
}

.cell:not(:disabled) {
  cursor: pointer;
}

.cell:not(:disabled):hover {
  background-color: #fafafa;
}
</style>

// packages/questions/user-interface/tic-tac-toe/frameworks/svelte/solution/setup/src/Cell.svelte
<script>
  export let index;
  export let disabled;
  export let mark;
  export let turn;

  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
</script>

<button
  aria-label={mark == null
    ? `Mark cell ${index} as ${turn}`
    : undefined}
  class="cell"
  {disabled}
  on:click={() => {
    dispatch('click');
  }}>
  <span aria-hidden={true}>{mark ?? ''}</span>
</button>

<style>
  .cell {
    background-color: #fff;
    border: 1px solid #ccc;
    color: #000;
    font-size: min(48px, 10vw);
    font-weight: bold;
    vertical-align: middle;
    aspect-ratio: 1 / 1;
  }

  .cell:not(:disabled) {
    cursor: pointer;
  }

  .cell:not(:disabled):hover {
    background-color: #fafafa;
  }
</style>
