// contents/questions/user-interface/tabs-iii/frameworks/angular/solution/setup/src/app/tabs.component.ts
import {
  Component,
  HostListener,
  Input,
} from '@angular/core';

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
})
export class TabsComponent {
  @Input()
  items!: any[];

  @Input()
  defaultValue!: string;

  value = '';
  tabsId =
    'tabs-' + Math.random().toString(36).substring(2, 9);

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    const currentIndex = this.items.findIndex(
      (item) => item.value === this.value,
    );
    switch (event.code) {
      case 'ArrowLeft':
        this.setValueViaIndex(
          (currentIndex - 1 + this.items.length) %
            this.items.length,
        );
        break;
      case 'ArrowRight':
        this.setValueViaIndex(
          (currentIndex + 1) % this.items.length,
        );
        break;
      case 'Home':
        this.setValueViaIndex(0);
        break;
      case 'End':
        this.setValueViaIndex(this.items.length - 1);
        break;
    }
  }

  ngOnInit(): void {
    this.value = this.defaultValue ?? this.items[0].value;
  }

  getTabListItemId(value: string): string {
    return `${this.tabsId}-tab-${value}`;
  }

  getTabPanelId(value: string): string {
    return `${this.tabsId}-tabpanel-${value}`;
  }

  setValue(newValue: string): void {
    this.value = newValue;
    const element = document.getElementById(
      this.getTabListItemId(newValue),
    );
    if (element) {
      element.focus();
    }
  }

  setValueViaIndex(index: number): void {
    const newValue = this.items[index].value;
    this.setValue(newValue);
  }
}

// packages/questions/user-interface/tabs-iii/frameworks/react/solution/setup/Tabs.js
import { useId, useState } from 'react';

function getTabListItemId(tabsId, value) {
  return tabsId + '-tab-' + value;
}

function getTabPanelId(tabsId, value) {
  return tabsId + '-tabpanel-' + value;
}

export default function Tabs({ defaultValue, items }) {
  const tabsId = useId();
  const [value, setValue] = useState(
    defaultValue ?? items[0].value,
  );

  function setValueViaIndex(index) {
    const newValue = items[index].value;
    setValue(newValue);
    document
      .getElementById(getTabListItemId(tabsId, newValue))
      .focus();
  }

  return (
    <div className="tabs">
      <div
        className="tabs-list"
        role="tablist"
        onKeyDown={(event) => {
          switch (event.code) {
            case 'ArrowLeft': {
              const index = items.findIndex(
                ({ value: itemValue }) =>
                  itemValue === value,
              );
              setValueViaIndex(
                // Use modulo to wrap around to the end if necessary.
                (index - 1 + items.length) % items.length,
              );
              break;
            }
            case 'ArrowRight': {
              const index = items.findIndex(
                ({ value: itemValue }) =>
                  itemValue === value,
              );
              // Use modulo to wrap around to the start if necessary.
              setValueViaIndex((index + 1) % items.length);
              break;
            }
            case 'Home': {
              // Set the first item ias the active item.
              setValueViaIndex(0);
              break;
            }
            case 'End': {
              // Set the last item ias the active item.
              setValueViaIndex(items.length - 1);
              break;
            }
            default:
              break;
          }
        }}>
        {items.map(({ label, value: itemValue }) => {
          const isActiveValue = itemValue === value;

          return (
            <button
              id={getTabListItemId(tabsId, itemValue)}
              key={itemValue}
              type="button"
              className={[
                'tabs-list-item',
                isActiveValue && 'tabs-list-item--active',
              ]
                .filter(Boolean)
                .join(' ')}
              onClick={() => {
                setValue(itemValue);
              }}
              role="tab"
              tabIndex={isActiveValue ? 0 : -1}
              aria-controls={getTabPanelId(
                tabsId,
                itemValue,
              )}
              aria-selected={isActiveValue}>
              {label}
            </button>
          );
        })}
      </div>
      <div>
        {items.map(({ panel, value: itemValue }) => (
          <div
            key={itemValue}
            tabIndex={0}
            id={getTabPanelId(tabsId, itemValue)}
            aria-labelledby={getTabListItemId(
              tabsId,
              itemValue,
            )}
            role="tabpanel"
            hidden={itemValue !== value}>
            {panel}
          </div>
        ))}
      </div>
    </div>
  );
}
