// packages/questions/user-interface/accordion-iii/frameworks/angular/solution/setup/src/app/accordion/accordion.component.ts
import {
  Component,
  HostListener,
  Input,
} from '@angular/core';
import { Section } from '../app.component';

export function generateId(): string {
  return Math.random().toString(36).substring(2);
}

@Component({
  selector: 'app-accordion',
  templateUrl: './accordion.component.html',
  styleUrls: ['./accordion.component.css'],
})
export class AccordionComponent {
  @Input()
  sections!: Section[];

  openSections = new Set<string>();
  accordionId = generateId();

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent): void {
    const activeElement =
      document.activeElement as HTMLElement;
    const activeItemValue = activeElement.getAttribute(
      'data-accordion-value',
    );

    if (activeItemValue == null) {
      return;
    }

    const index = this.sections.findIndex(
      (section) => section.value === activeItemValue,
    );

    switch (event.code) {
      case 'ArrowUp':
        this.focusOnSection(
          (index - 1 + this.sections.length) %
            this.sections.length,
        );
        break;
      case 'ArrowDown':
        this.focusOnSection(
          (index + 1) % this.sections.length,
        );
        break;
      case 'Home':
        this.focusOnSection(0);
        break;
      case 'End':
        this.focusOnSection(this.sections.length - 1);
        break;
      default:
        break;
    }
  }

  private focusOnSection(index: number): void {
    const section = this.sections[index];
    const headerId = this.getAccordionHeaderId(
      this.accordionId,
      section.value,
    );
    const element = document.getElementById(headerId);
    element?.focus();
  }

  getAccordionHeaderId(
    accordionId: string,
    value: string,
  ): string {
    return accordionId + '-header-' + value;
  }

  getAccordionPanelId(
    accordionId: string,
    value: string,
  ): string {
    return accordionId + '-panel-' + value;
  }

  isOpen(value: string): boolean {
    return this.openSections.has(value);
  }

  toggleSection(value: string): void {
    if (this.openSections.has(value)) {
      this.openSections.delete(value);
    } else {
      this.openSections.add(value);
    }
  }
}

// contents/questions/user-interface/accordion-iii/frameworks/react/solution/setup/src/Accordion.js
import { useId, useState } from 'react';

function getAccordionHeaderId(accordionId, value) {
  return accordionId + '-header-' + value;
}

function getAccordionPanelId(accordionId, value) {
  return accordionId + '-panel-' + value;
}

export default function Accordion({ sections }) {
  const accordionId = useId();
  const [openSections, setOpenSections] = useState(
    new Set(),
  );

  function focusOnSection(index) {
    document
      .getElementById(
        getAccordionHeaderId(
          accordionId,
          sections[index].value,
        ),
      )
      .focus();
  }

  return (
    <div
      className="accordion"
      onKeyDown={(event) => {
        const activeItemValue =
          document.activeElement.getAttribute(
            'data-accordion-value',
          );

        // Only respond to these interactions if
        // an accordion title is in focus.
        if (activeItemValue == null) {
          return;
        }

        switch (event.code) {
          case 'ArrowUp': {
            const index = sections.findIndex(
              ({ value: itemValue }) =>
                itemValue === activeItemValue,
            );
            focusOnSection(
              (index - 1 + sections.length) %
                sections.length,
            );
            break;
          }
          case 'ArrowDown': {
            const index = sections.findIndex(
              ({ value: itemValue }) =>
                itemValue === activeItemValue,
            );
            focusOnSection((index + 1) % sections.length);
            break;
          }
          case 'Home': {
            focusOnSection(0);
            break;
          }
          case 'End': {
            focusOnSection(sections.length - 1);
            break;
          }
          default:
            break;
        }
      }}>
      {sections.map(({ value, title, contents }) => {
        const isExpanded = openSections.has(value);
        const headerId = getAccordionHeaderId(
          accordionId,
          value,
        );
        const panelId = getAccordionPanelId(
          accordionId,
          value,
        );

        return (
          <div className="accordion-item" key={value}>
            <button
              aria-controls={panelId}
              aria-expanded={isExpanded}
              id={headerId}
              className="accordion-item-title"
              type="button"
              data-accordion-value={value}
              onClick={() => {
                const newOpenSections = new Set(
                  openSections,
                );
                newOpenSections.has(value)
                  ? newOpenSections.delete(value)
                  : newOpenSections.add(value);
                setOpenSections(newOpenSections);
              }}>
              {title}{' '}
              <span
                aria-hidden={true}
                className={[
                  'accordion-icon',
                  isExpanded && 'accordion-icon--rotated',
                ]
                  .filter(Boolean)
                  .join(' ')}
              />
            </button>
            <div
              aria-labelledby={headerId}
              role="region"
              className="accordion-item-contents"
              id={panelId}
              hidden={!isExpanded}>
              {contents}
            </div>
          </div>
        );
      })}
    </div>
  );
}
