// packages/questions/user-interface/like-button/frameworks/angular/solution/setup/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import {
  HttpClient,
  HttpErrorResponse,
} from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  liked = false;
  isPending = false;
  errorMessage: string | null = null;

  http = inject(HttpClient);

  likeUnlikeAction() {
    this.isPending = true;
    this.errorMessage = null;
    this.http
      .post(
        'https://www.greatfrontend.com/api/questions/like-button',
        {
          action: this.liked ? 'unlike' : 'like',
        },
      )
      .subscribe({
        next: () => {
          this.isPending = false;
          this.liked = !this.liked;
        },
        error: (error: HttpErrorResponse) => {
          this.isPending = false;
          this.errorMessage = error.error.message;
        },
      });
  }
}

// packages/questions/user-interface/like-button/frameworks/react/solution/setup/src/App.js
import { useState } from 'react';
import { HeartIcon, SpinnerIcon } from './icons';

import './styles.css';

function classNames(...args) {
  return args.filter(Boolean).join(' ');
}

export default function App() {
  // Determines if the button is in the default/liked state.
  const [liked, setLiked] = useState(false);
  // Whether there's a pending background API request.
  const [isPending, setIsPending] = useState(false);
  // Error message to be shown if the API request failed.
  const [errorMessage, setErrorMessage] = useState(null);

  async function likeUnlikeAction() {
    try {
      setIsPending(true);
      setErrorMessage(null);

      const response = await fetch(
        'https://www.greatfrontend.com/api/questions/like-button',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            action: liked ? 'unlike' : 'like',
          }),
        },
      );

      if (!response.ok) {
        const res = await response.json();
        setErrorMessage(res.error);
        return;
      }

      setLiked(!liked);
    } finally {
      setIsPending(false);
    }
  }

  return (
    <div className="button-container">
      <button
        className={classNames(
          'like-button',
          liked
            ? 'like-button--liked'
            : 'like-button--default',
        )}
        disabled={isPending}
        onClick={() => {
          likeUnlikeAction();
        }}>
        {isPending ? <SpinnerIcon /> : <HeartIcon />}
        {liked ? 'Liked' : 'Like'}
      </button>
      {errorMessage && (
        <div className="error-message">{errorMessage}</div>
      )}
    </div>
  );
}
