// contents/questions/user-interface/transfer-list/frameworks/vue/solution/setup/src/ItemList.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
  items: Map,
});

const entries = computed(() => Array.from(props.items));
</script>

<template>
  <div class="transfer-list__section">
    <ul class="transfer-list__section__items">
      <li v-for="[label, checked] in entries">
        <label>
          <input
            type="checkbox"
            :checked="checked"
            @change="$emit('toggle', label)" />
          {{ label }}
        </label>
      </li>
    </ul>
  </div>
</template>

<style>
ul {
  list-style-type: none;
  padding-left: 0;
}

.transfer-list__section {
  padding: 20px;
  flex-grow: 1;
}

.transfer-list__section__items {
  display: flex;
  flex-direction: column;
  row-gap: 12px;
}

.transfer-list__section__items__item {
  display: flex;
  gap: 8px;
}
</style>

// packages/questions/user-interface/transfer-list/frameworks/svelte/solution/setup/src/ItemList.svelte
<script>
  export let items;
</script>

<div class="transfer-list__section">
  <ul class="transfer-list__section__items">
    {#each Array.from(items.entries()) as [label, checked]}
      <li>
        <div class="transfer-list__section__items__item">
          <label>
            <input
              type="checkbox"
              {checked}
              on:change={() => {
                const newItems = new Map(items);
                newItems.set(label, !items.get(label));
                items = newItems;
              }} />
            {label}</label>
        </div>
      </li>
    {/each}
  </ul>
</div>

<style>
  ul {
    list-style-type: none;
    padding-left: 0;
  }

  .transfer-list__section {
    padding: 20px;
    flex-grow: 1;
  }

  .transfer-list__section__items {
    display: flex;
    flex-direction: column;
    row-gap: 12px;
  }

  .transfer-list__section__items__item {
    display: flex;
    gap: 8px;
  }
</style>
